In [1]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

'''
The variable list_ is a Python list, while the variable array_list is a NumPy array.
'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))     
print(type(array_list))  


<class 'list'>
<class 'numpy.ndarray'>


In [2]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
# Q3. Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

'''
Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list 
when the dtype parameter is set to int in the NumPy array.

The dtype parameter in the np.array() function is used to set the data type of the elements in the 
resulting NumPy array. When dtype is set to int, the elements in the array will be of integer data type.
'''

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
print(num_array.shape)  # Output: (2, 3)

# Find the size of num_array
print(num_array.size)   # Output: 6


(2, 3)
6


In [12]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.

import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

import numpy as np

zeros_array = np.eye(5, 5)

print(zeros_array)




[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
